### ISSUE TITLE
Task 9

### ISSUE THREAD

**Issue by Felipe-Hub** [ironhack-labs/lab-sql-7#1]
@sandrabosk 

Could not find a solution for task 9 that uses the tools learned so far (the suggested solution is not working, since alias and window functions are not supported in 'where' clauses). Workaround would be with subqueries, but it is a topic to be presented in the next unit.

Workaround:
select * from (select rental_id, inventory_id, datediff(return_date, rental_date) num_days, avg(datediff(return_date, rental_date)) over (partition by inventory_id) avg_return_days
from rental) as t
where t.num_days < t.avg_return_days;

**Comment by haggarw3** [comment]
Yes this looks like a question for the next topics , so I have removed this question from this activity

**Comment by ironhack-edu** [comment]
Solved, merged. Thank you both!
